# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: false
warnings_are_errors: true
after_success:
  - Rscript -e 'covr::codecov(type = "all")'
before_cache: Rscript -e 'install.packages("pkgdown", repos = "https://cloud.r-project.org/")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY"))'
  skip_cleanup: true
